//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.BAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RehabilitationInstitutes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RehabilitationInstitutes()
        {
            this.DisasterInformation = new HashSet<DisasterInformation>();
            this.PublicMessage = new HashSet<PublicMessage>();
            this.ReliefInformation = new HashSet<ReliefInformation>();
        }
    
        public int RehabilitationInstituteID { get; set; }
        public Nullable<int> NDMAUserID { get; set; }
        public string InstituteName { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisasterInformation> DisasterInformation { get; set; }
        public virtual NDMAUser NDMAUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicMessage> PublicMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReliefInformation> ReliefInformation { get; set; }
    }
}
