//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.BAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReliefInformation
    {
        public int ReliefInformationID { get; set; }
        public Nullable<int> RehabilitationInstituteID { get; set; }
        public Nullable<int> NDMAUserId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateGranted { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual NDMAUser NDMAUser { get; set; }
        public virtual RehabilitationInstitutes RehabilitationInstitutes { get; set; }
    }
}
